"""update project and institute table to allow for relationship

Revision ID: 00276a8cfe1e
Revises: 9ecaf8b6cd44
Create Date: 2025-09-08 12:02:46.543401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00276a8cfe1e'
down_revision = '9ecaf8b6cd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_institute_id_institutes'), 'institutes', ['institute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_institute_id_institutes'), type_='foreignkey')
        batch_op.drop_column('institute_id')

    # ### end Alembic commands ###
