"""create points table

Revision ID: 0ba4ed06850a
Revises: 00276a8cfe1e
Create Date: 2025-09-08 14:48:49.916502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba4ed06850a'
down_revision = '00276a8cfe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_point', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_point_id_project_points'), 'project_points', ['point_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_point_id_project_points'), type_='foreignkey')
        batch_op.drop_column('point_id')

    op.drop_table('project_points')
    # ### end Alembic commands ###
