"""create api project table

Revision ID: 1b32b8425e0d
Revises: 58101f6dadd9
Create Date: 2025-10-08 08:49:37.737612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b32b8425e0d'
down_revision = '58101f6dadd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['APIs.id'], name=op.f('fk_api_projects_api_id_APIs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_projects_project_id_projects')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_projects')
    # ### end Alembic commands ###
