"""update api-tech table

Revision ID: 244ac0ba691d
Revises: b4d39db874cb
Create Date: 2025-10-23 08:28:06.369048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244ac0ba691d'
down_revision = 'b4d39db874cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_id', sa.Integer(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_api_projects_tech_id_technologies'), 'technologies', ['tech_id'], ['id'])
        batch_op.drop_column('api_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_api_projects_tech_id_technologies'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'APIs', ['api_id'], ['id'])
        batch_op.drop_column('tech_id')

    # ### end Alembic commands ###
