"""update project paragraph model

Revision ID: 2af0a1bbfb75
Revises: 244ac0ba691d
Create Date: 2025-11-05 11:59:54.819996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af0a1bbfb75'
down_revision = '244ac0ba691d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('APIs')
    with op.batch_alter_table('project_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paragraph_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('paragraph_title')

    op.create_table('APIs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
