"""create project paragraph table

Revision ID: 362f587e86d8
Revises: 3cd634657aff
Create Date: 2025-09-08 15:49:26.597971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362f587e86d8'
down_revision = '3cd634657aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph', sa.String(), nullable=True),
    sa.Column('paragraph_img_1', sa.String(), nullable=True),
    sa.Column('paragraph_img_2', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_paragraphs_project_id_projects')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_paragraphs')
    # ### end Alembic commands ###
