"""upgrade project and points table

Revision ID: 3cd634657aff
Revises: 0ba4ed06850a
Create Date: 2025-09-08 14:51:09.175219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd634657aff'
down_revision = '0ba4ed06850a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project_points_project_id_projects'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_point_id_project_points', type_='foreignkey')
        batch_op.drop_column('point_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_projects_point_id_project_points', 'project_points', ['point_id'], ['id'])

    with op.batch_alter_table('project_points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_points_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
