"""create api table

Revision ID: 58101f6dadd9
Revises: 5d6715c7ea07
Create Date: 2025-10-08 08:11:07.941974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58101f6dadd9'
down_revision = '5d6715c7ea07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APIs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('APIs')
    # ### end Alembic commands ###
