"""update socials table

Revision ID: 5b4b8c26248a
Revises: 1b32b8425e0d
Create Date: 2025-10-11 21:51:45.991293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4b8c26248a'
down_revision = '1b32b8425e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_points', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_points_project_id_projects', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project_points_project_id_projects'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('project_points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_points_project_id_projects'), type_='foreignkey')
        batch_op.create_foreign_key('fk_project_points_project_id_projects', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
