"""add frontend tech table

Revision ID: 5d6715c7ea07
Revises: 8aad072a7103
Create Date: 2025-09-12 10:34:29.775621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6715c7ea07'
down_revision = '8aad072a7103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_end_tech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_front_end_tech_project_id_projects')),
    sa.ForeignKeyConstraint(['tech_id'], ['technologies.id'], name=op.f('fk_front_end_tech_tech_id_technologies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('front_end_tech')
    # ### end Alembic commands ###
