"""create qualifications table

Revision ID: 73efdfc10219
Revises: 34f0f9e766ed
Create Date: 2025-09-10 10:02:39.937951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73efdfc10219'
down_revision = '34f0f9e766ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.Column('qualification_img', sa.String(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], name=op.f('fk_qualifications_institute_id_institutes')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualifications')
    # ### end Alembic commands ###
