"""add backend table

Revision ID: 8aad072a7103
Revises: addf3bb09080
Create Date: 2025-09-12 10:03:52.858096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aad072a7103'
down_revision = 'addf3bb09080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_tech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_backend_tech_project_id_projects')),
    sa.ForeignKeyConstraint(['tech_id'], ['technologies.id'], name=op.f('fk_backend_tech_tech_id_technologies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backend_tech')
    # ### end Alembic commands ###
