"""add institute table

Revision ID: 9ecaf8b6cd44
Revises: 76a91eb9647a
Create Date: 2025-09-08 11:27:05.863401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecaf8b6cd44'
down_revision = '76a91eb9647a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_name', sa.String(), nullable=True),
    sa.Column('institute_img', sa.String(), nullable=True),
    sa.Column('institute_start_date', sa.Date(), nullable=True),
    sa.Column('institute_end_date', sa.Date(), nullable=True),
    sa.Column('institute_city', sa.String(), nullable=True),
    sa.Column('institute_country', sa.String(), nullable=True),
    sa.Column('institute_intro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institutes')
    # ### end Alembic commands ###
