"""create project tech table

Revision ID: adf863bf8626
Revises: be01e75c374a
Create Date: 2025-09-09 11:35:01.273703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf863bf8626'
down_revision = 'be01e75c374a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.Column('front_end', sa.Boolean(), nullable=True),
    sa.Column('back_end', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_technology_project_id_projects')),
    sa.ForeignKeyConstraint(['tech_id'], ['technologies.id'], name=op.f('fk_project_technology_tech_id_technologies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_technology')
    # ### end Alembic commands ###
