"""add cloud project table

Revision ID: b4d39db874cb
Revises: f745bfb49889
Create Date: 2025-10-19 09:55:54.834988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d39db874cb'
down_revision = 'f745bfb49889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cloud_projects_project_id_projects')),
    sa.ForeignKeyConstraint(['tech_id'], ['technologies.id'], name=op.f('fk_cloud_projects_tech_id_technologies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_projects')
    # ### end Alembic commands ###
