"""update technology model

Revision ID: e86108451d1e
Revises: 5b4b8c26248a
Create Date: 2025-10-16 08:57:36.246951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86108451d1e'
down_revision = '5b4b8c26248a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tech_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.drop_column('tech_type')

    # ### end Alembic commands ###
