"""add columns to project model

Revision ID: f745bfb49889
Revises: 31e5c48979c7
Create Date: 2025-10-18 21:51:30.354477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f745bfb49889'
down_revision = '31e5c48979c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('github_url')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
