"""add paragraph table

Revision ID: 439c8713af9d
Revises: 0cdbf2288646
Create Date: 2025-08-19 11:10:05.403124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439c8713af9d'
down_revision = '0cdbf2288646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('img_1', sa.String(), nullable=True),
    sa.Column('img_2', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_paragraphs_project_id_projects')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraphs')
    # ### end Alembic commands ###
