"""create emails table

Revision ID: 708bad8aa14c
Revises: 5fb1a208bba7
Create Date: 2025-08-21 14:35:45.207610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708bad8aa14c'
down_revision = '5fb1a208bba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
