"""add an email column to user table

Revision ID: 72caf2c34106
Revises: e0a14d14d1dc
Create Date: 2025-08-23 12:00:25.055111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72caf2c34106'
down_revision = 'e0a14d14d1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), server_default='default_value', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
