"""add a qualification table

Revision ID: a542a65bb2bd
Revises: eb26dd894305
Create Date: 2025-08-19 13:08:13.680547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a542a65bb2bd'
down_revision = 'eb26dd894305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('img_1', sa.String(), nullable=False),
    sa.Column('img_2', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], name=op.f('fk_qualifications_institute_id_institutes')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('img_1'),
    sa.UniqueConstraint('img_2'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualifications')
    # ### end Alembic commands ###
